const std = @import("std");
const Io = std.Io;
const Writer = Io.Writer;
const ffmig = @import("ffmig");
const config = ffmig.config;
const Env = ffmig.commands.Env;
const check = ffmig.commands.check;
const run = check.run;
const usage = check.usage;

const testing = std.testing;

const Result = struct {
    code: u8,
    out: Writer.Allocating,
    err: Writer.Allocating,

    fn deinit(r: *Result) void {
        r.out.deinit();
        r.err.deinit();
    }
};

fn checkIn(dir: Io.Dir, args: []const []const u8) !Result {
    var r: Result = .{
        .code = undefined,
        .out = .init(testing.allocator),
        .err = .init(testing.allocator),
    };
    const env: Env = .{ .io = testing.io, .cwd = dir, .gpa = testing.allocator };
    r.code = try run(env, args, &r.out.writer, &r.err.writer);
    return r;
}

fn writeFile(dir: Io.Dir, path: []const u8, data: []const u8) !void {
    if (std.fs.path.dirname(path)) |parent| try dir.createDirPath(testing.io, parent);
    try dir.writeFile(testing.io, .{ .sub_path = path, .data = data });
}

const empty_migration = "migration CreateUsers {\n  change {\n  }\n}\n";

test "check passes a migration generated by new" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    try writeFile(tmp.dir, config.file_name, "[migration]\npath = \"db/migrations\"\n");

    var created: Writer.Allocating = .init(testing.allocator);
    defer created.deinit();
    var ignored: Writer.Allocating = .init(testing.allocator);
    defer ignored.deinit();
    const env: Env = .{ .io = testing.io, .cwd = tmp.dir, .gpa = testing.allocator };
    try testing.expectEqual(0, try ffmig.commands.new.run(env, &.{"CreateUsers"}, &created.writer, &ignored.writer));

    var r = try checkIn(tmp.dir, &.{});
    defer r.deinit();
    try testing.expectEqual(0, r.code);
    // "Created <path>\n" -> "ok <path>\n"
    const path = created.written()["Created ".len..];
    const expected = try std.mem.concat(testing.allocator, u8, &.{ "ok ", path });
    defer testing.allocator.free(expected);
    try testing.expectEqualStrings(expected, r.out.written());
    try testing.expectEqualStrings("", r.err.written());
}

test "check reports file:line:col, the source line and a caret" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    try writeFile(tmp.dir, "a.mig", "migration AddIndex {\n  change {\n\tadd_index :users, :email, uniq: true\n  }\n}\n");

    var r = try checkIn(tmp.dir, &.{"a.mig"});
    defer r.deinit();
    try testing.expectEqual(1, r.code);
    try testing.expectEqualStrings("", r.out.written());
    try testing.expectEqualStrings(
        "a.mig:3:28: unknown option 'uniq' for add_index\n" ++
            "\tadd_index :users, :email, uniq: true\n" ++
            "\t" ++ " " ** 26 ++ "^~~~~\n",
        r.err.written(),
    );
}

test "check reports a syntax error at end of file" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    try writeFile(tmp.dir, "a.mig", "migration M {\n  change {\n");

    var r = try checkIn(tmp.dir, &.{"a.mig"});
    defer r.deinit();
    try testing.expectEqual(1, r.code);
    try testing.expectEqualStrings(
        \\a.mig:2:3: expected '}' to close 'change' block opened here
        \\  change {
        \\  ^~~~~~
        \\
    , r.err.written());
}

test "check keeps going and reports every broken file in order" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    try writeFile(tmp.dir, config.file_name, "[migration]\npath = \"migrations\"\n");
    try writeFile(tmp.dir, "migrations/20260102000000_b.mig", "migration B { change { add_idx :t, :c } }\n");
    try writeFile(tmp.dir, "migrations/20260101000000_a.mig", empty_migration);
    try writeFile(tmp.dir, "migrations/20260103000000_c.mig", "migration C { up { } }\n");
    try writeFile(tmp.dir, "migrations/20260104000000_d.mig", empty_migration);
    try writeFile(tmp.dir, "migrations/notes.txt", "not a migration");

    var r = try checkIn(tmp.dir, &.{});
    defer r.deinit();
    try testing.expectEqual(1, r.code);
    try testing.expectEqualStrings(
        \\ok migrations/20260101000000_a.mig
        \\ok migrations/20260104000000_d.mig
        \\
    , r.out.written());
    try testing.expectEqualStrings(
        \\migrations/20260102000000_b.mig:1:24: unknown operation 'add_idx'
        \\migration B { change { add_idx :t, :c } }
        \\                       ^~~~~~~
        \\migrations/20260103000000_c.mig:1:15: missing 'down' block
        \\migration C { up { } }
        \\              ^~
        \\
    , r.err.written());
}

test "check with files ignores the config and reports unreadable files" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    try writeFile(tmp.dir, "x/a.mig", empty_migration);

    var r = try checkIn(tmp.dir, &.{ "x/a.mig", "missing.mig" });
    defer r.deinit();
    try testing.expectEqual(1, r.code);
    try testing.expectEqualStrings("ok x/a.mig\n", r.out.written());
    try testing.expectEqualStrings("ffmig: cannot read missing.mig: FileNotFound\n", r.err.written());
}

test "check --ast prints the lowered migration" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    try writeFile(tmp.dir, "a.mig",
        \\migration AddRole {
        \\  up {
        \\    add_column :users, :role, :integer, null: false, default: 0
        \\  }
        \\  down {
        \\    remove_column :users, :role
        \\  }
        \\}
        \\
    );

    var r = try checkIn(tmp.dir, &.{ "--ast", "a.mig" });
    defer r.deinit();
    try testing.expectEqual(0, r.code);
    try testing.expectEqualStrings(
        \\ok a.mig
        \\migration AddRole
        \\  up
        \\    add_column users
        \\      column role integer not_null default=0
        \\  down
        \\    remove_column users role
        \\
    , r.out.written());
}

test "check without files needs ffmig.toml" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();

    var r = try checkIn(tmp.dir, &.{});
    defer r.deinit();
    try testing.expectEqual(1, r.code);
    try testing.expectEqualStrings("ffmig: ffmig.toml not found; run 'ffmig init' first\n", r.err.written());
}

test "check rejects unknown flags" {
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();

    var r = try checkIn(tmp.dir, &.{"--nope"});
    defer r.deinit();
    try testing.expectEqual(1, r.code);
    try testing.expectEqualStrings(usage, r.err.written());
}
