-- up
ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 1;
ALTER TABLE "posts" ALTER COLUMN "published_at" SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "users" ALTER COLUMN "name" DROP DEFAULT;
-- down
ALTER TABLE "users" ALTER COLUMN "name" SET DEFAULT 'it''s';
ALTER TABLE "posts" ALTER COLUMN "published_at" DROP DEFAULT;
ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 0;
